#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config borderless_monocle    true
bspc config gapless_monocle       true
#Autostart app
sxhkd & 
picom --config $HOME/.config/picom/picom.conf &
nitrogen --restore &
dunst &
polybar &
flameshot &

#Windows rules

bspc rule -a mpv desktop='^4' follow=on


#xrandr --output Virtual-1 --mode 1920x1080

xrandr --newmode "2560x1440_60.00"  312.25  2560 2752 3024 3488  1440 1443 1448 1493 -hsync +vsync
xrandr --addmode Virtual-1 "2560x1440_60.00"
xrandr --output Virtual-1 --mode "2560x1440_60.00"
