#!/bin/sh

#LAUNCHERS
$HOME/.config/bspwm/autostart.sh

#BSPWM configuration
bspc config border_width        2
bspc config window_gap          5

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
bspc config top_padding          20
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0


#BSPWM coloring
bspc config normal_border_color		"#444444"
bspc config active_border_color		"#444444"
bspc config focused_border_color	"#444444"


#Single monitor
bspc monitor -d '1' '2' '3' '4' '5' '6' '7' '8' '9'

#More edits
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

#Fullscreen applications

bspc rule -a Vlc state=fullscreen

#Floating applications
bspc rule -a Arandr state=floating
bspc rule -a Archlinux-tweak-tool.py state=floating
bspc rule -a Arcolinux-welcome-app.py state=floating
bspc rule -a Arcolinux-calamares-tool.py state=floating
bspc rule -a feh state=floating
bspc rule -a Galculator state=floating
bspc rule -a Nitrogen state=floating
bspc rule -a Oblogout state=floating
bspc rule -a Xfce4-terminal state=floating

#Tiled applications
bspc rule -a Gnome-disks state=tiled
bspc rule -a Xfce4-settings-manager state=tiled

#open applications on specific workspaces

#bspc rule -a Vivaldi-stable desktop='^6' follow=on
#bspc rule -a Vivaldi-snapshot desktop='^6' follow=on


polybar hidden when fullscreen for vlc, youtube, mpv ...
